import os

POSTGRES_USERNAME = os.environ.get("POSTGRES_USERNAME", "")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD", "")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST", "")
POSTGRES_PORT = os.environ.get("POSTGRES_PORT", "")
POSTGRES_DBNAME = os.environ.get("POSTGRES_DBNAME", "")
POSTGRES_USERNAME_DB_SOL = os.environ.get("POSTGRES_USERNAME_DB_SOL", "")
POSTGRES_PASSWORD_DB_SOL = os.environ.get("POSTGRES_PASSWORD_DB_SOL", "")
POSTGRES_HOST_DB_SOL = os.environ.get("POSTGRES_HOST_DB_SOL", "")
POSTGRES_PORT_DB_SOL = os.environ.get("POSTGRES_PORT_DB_SOL", "")
POSTGRES_DBNAME_DB_SOL = os.environ.get("POSTGRES_DBNAME_DB_SOL", "")

INFRA_URL = os.environ.get("INFRA_URL", "")
POKT_URL = os.environ.get("POKT_URL", "")
POKT_URL_SECOND = os.environ.get(
    "POKT_URL_SECOND", ""
)
OWN_NODE_URL = os.environ.get("OWN_NODE_URL", "")
API_KEY_ETHERSCAN = os.environ.get("API_KEY_ETHERSCAN", "")

REDIS_URL = os.environ.get("REDIS_URL", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")

RABBIT_MQ = os.environ.get("RABBIT_MQ", "amqp://rabbitmq//")
RABBIT_MQ_LOCAL = os.environ.get("RABBIT_MQ_LOCAL", "amqp://localhost:5672//")

DIVIDER = 10**18  # для перевода в эфир

NAME_MAIN_QUEUE_TRX = os.environ.get("NAME_MAIN_QUEUE_TRX", "queue_trx")

possible_uri_names = ["uri", "tokenURI"]
possible_is_nft_names = ["isNonFungible"]
possible_supply_count_names = ["totalsupply", "maxsupply", "totaltokens", "totalminted"]
possible_release_data_names = ["publicsalestart", "release", "release_date", "starttime"]
possible_implementation = ["implementation"]

possible_image_json = ["image_url", "image"]
possible_total_supply_json = ["groupSize"]
possible_name_collect_json = ["collection"]
possible_name_token_json = ["name", "card_name"]

NULL_ADDRESS = "0x0000000000000000000000000000000000000000"

download_manager_url = os.environ.get("download_manager_url", "")
OpenSea_contract_1155 = "0x495f947276749ce646f68ac8c248420045cb7b5e"
CryptoKitties_contract = "0x06012c8cf97bead5deae237070f9587f8e7a266d"
CryptoPunks_contract = "0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb"

proxies = {"http": "socks5://", "https": "socks5://"}

ipfs_public_gateways = [
    "https://ipfs.io/ipfs/",
    "http://ipfs.genenetwork.org/ipfs/",
    "https://ipfs.adatools.io/ipfs/",
    "https://via0.com/ipfs/",
    "https://cloudflare-ipfs.com/ipfs/",
    "https://ipfs.rhapsodylabs.xyz/ipfs/",
]

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Site": "cross-site",
}

REWARDS = {
    5: (0, 4369999 + 1),
    3: (4370000, 7279999 + 1),  # EIP-649 - Byzantium
    2: (7280000, 999999999),  # EIP-1234 - Constantinople
}
BURN_FEE_BLOCK = 12965000

WEI_TO_ETH_COUNT = 10**18

abi_owner_of = [
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "ownerOf",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    }
]

abi_coins = [
    {
        "constant": True,
        "inputs": [],
        "name": "name",
        "outputs": [{"name": "", "type": "string"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_upgradedAddress", "type": "address"}],
        "name": "deprecate",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_spender", "type": "address"}, {"name": "_value", "type": "uint256"}],
        "name": "approve",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "deprecated",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_evilUser", "type": "address"}],
        "name": "addBlackList",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "totalSupply",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {"name": "_from", "type": "address"},
            {"name": "_to", "type": "address"},
            {"name": "_value", "type": "uint256"},
        ],
        "name": "transferFrom",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "upgradedAddress",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "", "type": "address"}],
        "name": "balances",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "decimals",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "maximumFee",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "_totalSupply",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "unpause",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "_maker", "type": "address"}],
        "name": "getBlackListStatus",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "", "type": "address"}, {"name": "", "type": "address"}],
        "name": "allowed",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "paused",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "who", "type": "address"}],
        "name": "balanceOf",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "pause",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getOwner",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "owner",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "symbol",
        "outputs": [{"name": "", "type": "string"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_to", "type": "address"}, {"name": "_value", "type": "uint256"}],
        "name": "transfer",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "newBasisPoints", "type": "uint256"}, {"name": "newMaxFee", "type": "uint256"}],
        "name": "setParams",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "amount", "type": "uint256"}],
        "name": "issue",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "amount", "type": "uint256"}],
        "name": "redeem",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "_owner", "type": "address"}, {"name": "_spender", "type": "address"}],
        "name": "allowance",
        "outputs": [{"name": "remaining", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "basisPointsRate",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "", "type": "address"}],
        "name": "isBlackListed",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_clearedUser", "type": "address"}],
        "name": "removeBlackList",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "MAX_UINT",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_blackListedUser", "type": "address"}],
        "name": "destroyBlackFunds",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_initialSupply", "type": "uint256"},
            {"name": "_name", "type": "string"},
            {"name": "_symbol", "type": "string"},
            {"name": "_decimals", "type": "uint256"},
        ],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "amount", "type": "uint256"}],
        "name": "Issue",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "amount", "type": "uint256"}],
        "name": "Redeem",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "newAddress", "type": "address"}],
        "name": "Deprecate",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "name": "feeBasisPoints", "type": "uint256"},
            {"indexed": False, "name": "maxFee", "type": "uint256"},
        ],
        "name": "Params",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "name": "_blackListedUser", "type": "address"},
            {"indexed": False, "name": "_balance", "type": "uint256"},
        ],
        "name": "DestroyedBlackFunds",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "_user", "type": "address"}],
        "name": "AddedBlackList",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "_user", "type": "address"}],
        "name": "RemovedBlackList",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "owner", "type": "address"},
            {"indexed": True, "name": "spender", "type": "address"},
            {"indexed": False, "name": "value", "type": "uint256"},
        ],
        "name": "Approval",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "from", "type": "address"},
            {"indexed": True, "name": "to", "type": "address"},
            {"indexed": False, "name": "value", "type": "uint256"},
        ],
        "name": "Transfer",
        "type": "event",
    },
    {"anonymous": False, "inputs": [], "name": "Pause", "type": "event"},
    {"anonymous": False, "inputs": [], "name": "Unpause", "type": "event"},
]


abi_721 = [
    {
        "inputs": [],
        "name": "implementation",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "name",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "tokenURI",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "ownerOf",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalSupply",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "index", "type": "uint256"}],
        "name": "tokenByIndex",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
]

Transfer_erc_721 = "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"

abi_standard = [
    {
        "inputs": [
            {"internalType": "contract IGatewayHandler", "name": "gatewayHandler_", "type": "address"},
            {"internalType": "address", "name": "dava_", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "account", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "operator", "type": "address"},
            {"indexed": False, "internalType": "bool", "name": "approved", "type": "bool"},
        ],
        "name": "ApprovalForAll",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "previousOwner", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "newOwner", "type": "address"},
        ],
        "name": "OwnershipTransferred",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "internalType": "uint256", "name": "partId", "type": "uint256"}],
        "name": "PartCreated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"indexed": True, "internalType": "bytes32", "name": "previousAdminRole", "type": "bytes32"},
            {"indexed": True, "internalType": "bytes32", "name": "newAdminRole", "type": "bytes32"},
        ],
        "name": "RoleAdminChanged",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"indexed": True, "internalType": "address", "name": "account", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "sender", "type": "address"},
        ],
        "name": "RoleGranted",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"indexed": True, "internalType": "address", "name": "account", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "sender", "type": "address"},
        ],
        "name": "RoleRevoked",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "operator", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "from", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "to", "type": "address"},
            {"indexed": False, "internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
            {"indexed": False, "internalType": "uint256[]", "name": "values", "type": "uint256[]"},
        ],
        "name": "TransferBatch",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "operator", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "from", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "to", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"},
            {"indexed": False, "internalType": "uint256", "name": "value", "type": "uint256"},
        ],
        "name": "TransferSingle",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "string", "name": "value", "type": "string"},
            {"indexed": True, "internalType": "uint256", "name": "id", "type": "uint256"},
        ],
        "name": "URI",
        "type": "event",
    },
    {
        "inputs": [],
        "name": "CREATOR_ROLE",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "DAVA_GATEWAY_KEY",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "DEFAULT_ADMIN_ROLE",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "DEFAULT_CATEGORY",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "IPFS_GATEWAY_KEY",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "MINTER_ROLE",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "account", "type": "address"},
            {"internalType": "uint256", "name": "id", "type": "uint256"},
        ],
        "name": "balanceOf",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address[]", "name": "accounts", "type": "address[]"},
            {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
        ],
        "name": "balanceOfBatch",
        "outputs": [{"internalType": "uint256[]", "name": "", "type": "uint256[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "categoryId",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes32", "name": "categoryId_", "type": "bytes32"}],
        "name": "categoryInfo",
        "outputs": [
            {"internalType": "string", "name": "title_", "type": "string"},
            {"internalType": "uint256", "name": "backgroundImgTokenId_", "type": "uint256"},
            {"internalType": "uint256", "name": "foregroundImgTokenId_", "type": "uint256"},
            {"internalType": "uint256", "name": "zIndex_", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "categoryTitle",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "title_", "type": "string"},
            {"internalType": "uint256", "name": "backgroundImageTokenId_", "type": "uint256"},
            {"internalType": "uint256", "name": "foregroundImageTokenId_", "type": "uint256"},
            {"internalType": "uint256", "name": "zIndex_", "type": "uint256"},
        ],
        "name": "createCategory",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "categoryId_", "type": "bytes32"},
            {"internalType": "string", "name": "title_", "type": "string"},
            {"internalType": "string", "name": "description_", "type": "string"},
            {"internalType": "string", "name": "ipfsHash_", "type": "string"},
            {
                "components": [
                    {"internalType": "string", "name": "trait_type", "type": "string"},
                    {"internalType": "string", "name": "value", "type": "string"},
                ],
                "internalType": "struct IPartCollection.Attribute[]",
                "name": "attributes",
                "type": "tuple[]",
            },
            {"internalType": "uint256", "name": "maxSupply_", "type": "uint256"},
        ],
        "name": "createPart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "dava",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "description",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "exists",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "gatewayHandler",
        "outputs": [{"internalType": "contract IGatewayHandler", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getAllSupportedCategoryIds",
        "outputs": [{"internalType": "bytes32[]", "name": "", "type": "bytes32[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes32", "name": "role", "type": "bytes32"}],
        "name": "getRoleAdmin",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"internalType": "address", "name": "account", "type": "address"},
        ],
        "name": "grantRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"internalType": "address", "name": "account", "type": "address"},
        ],
        "name": "hasRole",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "image",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "imageUri",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "account", "type": "address"},
            {"internalType": "address", "name": "operator", "type": "address"},
        ],
        "name": "isApprovedForAll",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "maxSupply",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "account", "type": "address"},
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "bytes", "name": "data", "type": "bytes"},
        ],
        "name": "mint",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
            {"internalType": "uint256[]", "name": "amounts", "type": "uint256[]"},
            {"internalType": "bytes", "name": "data", "type": "bytes"},
        ],
        "name": "mintBatch",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "name",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "pure",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "numberOfParts",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "partTitle",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {"inputs": [], "name": "renounceOwnership", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
    {
        "inputs": [
            {"internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"internalType": "address", "name": "account", "type": "address"},
        ],
        "name": "renounceRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"internalType": "address", "name": "account", "type": "address"},
        ],
        "name": "revokeRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "from", "type": "address"},
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
            {"internalType": "uint256[]", "name": "amounts", "type": "uint256[]"},
            {"internalType": "bytes", "name": "data", "type": "bytes"},
        ],
        "name": "safeBatchTransferFrom",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "from", "type": "address"},
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "bytes", "name": "data", "type": "bytes"},
        ],
        "name": "safeTransferFrom",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "operator", "type": "address"},
            {"internalType": "bool", "name": "approved", "type": "bool"},
        ],
        "name": "setApprovalForAll",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes4", "name": "interfaceId", "type": "bytes4"}],
        "name": "supportsInterface",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "totalSupply",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "categoryId_", "type": "bytes32"},
            {"internalType": "string", "name": "title_", "type": "string"},
            {"internalType": "string", "name": "description_", "type": "string"},
            {"internalType": "string", "name": "ipfsHash_", "type": "string"},
            {
                "components": [
                    {"internalType": "string", "name": "trait_type", "type": "string"},
                    {"internalType": "string", "name": "value", "type": "string"},
                ],
                "internalType": "struct IPartCollection.Attribute[]",
                "name": "attributes",
                "type": "tuple[]",
            },
            {"internalType": "uint256", "name": "maxSupply_", "type": "uint256"},
            {"internalType": "uint256", "name": "filledSupply_", "type": "uint256"},
        ],
        "name": "unsafeCreatePart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
            {"internalType": "uint256[]", "name": "amounts", "type": "uint256[]"},
        ],
        "name": "unsafeMintBatch",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "uri",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "zIndex",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
]

abi_standard_change_name_args = [
    {
        "inputs": [
            {"internalType": "contract IGatewayHandler", "name": "gatewayHandler_", "type": "address"},
            {"internalType": "address", "name": "dava_", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "account", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "operator", "type": "address"},
            {"indexed": False, "internalType": "bool", "name": "approved", "type": "bool"},
        ],
        "name": "ApprovalForAll",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "previousOwner", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "newOwner", "type": "address"},
        ],
        "name": "OwnershipTransferred",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "internalType": "uint256", "name": "partId", "type": "uint256"}],
        "name": "PartCreated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"indexed": True, "internalType": "bytes32", "name": "previousAdminRole", "type": "bytes32"},
            {"indexed": True, "internalType": "bytes32", "name": "newAdminRole", "type": "bytes32"},
        ],
        "name": "RoleAdminChanged",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"indexed": True, "internalType": "address", "name": "account", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "sender", "type": "address"},
        ],
        "name": "RoleGranted",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"indexed": True, "internalType": "address", "name": "account", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "sender", "type": "address"},
        ],
        "name": "RoleRevoked",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "_operator", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "_from", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "_to", "type": "address"},
            {"indexed": False, "internalType": "uint256[]", "name": "_ids", "type": "uint256[]"},
            {"indexed": False, "internalType": "uint256[]", "name": "_values", "type": "uint256[]"},
        ],
        "name": "TransferBatch",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "operator", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "from", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "to", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"},
            {"indexed": False, "internalType": "uint256", "name": "value", "type": "uint256"},
        ],
        "name": "TransferSingle",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "string", "name": "_value", "type": "string"},
            {"indexed": True, "internalType": "uint256", "name": "_id", "type": "uint256"},
        ],
        "name": "URI",
        "type": "event",
    },
    {
        "inputs": [],
        "name": "CREATOR_ROLE",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "DAVA_GATEWAY_KEY",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "DEFAULT_ADMIN_ROLE",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "DEFAULT_CATEGORY",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "IPFS_GATEWAY_KEY",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "MINTER_ROLE",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "account", "type": "address"},
            {"internalType": "uint256", "name": "id", "type": "uint256"},
        ],
        "name": "balanceOf",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address[]", "name": "accounts", "type": "address[]"},
            {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
        ],
        "name": "balanceOfBatch",
        "outputs": [{"internalType": "uint256[]", "name": "", "type": "uint256[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "categoryId",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes32", "name": "categoryId_", "type": "bytes32"}],
        "name": "categoryInfo",
        "outputs": [
            {"internalType": "string", "name": "title_", "type": "string"},
            {"internalType": "uint256", "name": "backgroundImgTokenId_", "type": "uint256"},
            {"internalType": "uint256", "name": "foregroundImgTokenId_", "type": "uint256"},
            {"internalType": "uint256", "name": "zIndex_", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "categoryTitle",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "title_", "type": "string"},
            {"internalType": "uint256", "name": "backgroundImageTokenId_", "type": "uint256"},
            {"internalType": "uint256", "name": "foregroundImageTokenId_", "type": "uint256"},
            {"internalType": "uint256", "name": "zIndex_", "type": "uint256"},
        ],
        "name": "createCategory",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "categoryId_", "type": "bytes32"},
            {"internalType": "string", "name": "title_", "type": "string"},
            {"internalType": "string", "name": "description_", "type": "string"},
            {"internalType": "string", "name": "ipfsHash_", "type": "string"},
            {
                "components": [
                    {"internalType": "string", "name": "trait_type", "type": "string"},
                    {"internalType": "string", "name": "value", "type": "string"},
                ],
                "internalType": "struct IPartCollection.Attribute[]",
                "name": "attributes",
                "type": "tuple[]",
            },
            {"internalType": "uint256", "name": "maxSupply_", "type": "uint256"},
        ],
        "name": "createPart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "dava",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "description",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "exists",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "gatewayHandler",
        "outputs": [{"internalType": "contract IGatewayHandler", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getAllSupportedCategoryIds",
        "outputs": [{"internalType": "bytes32[]", "name": "", "type": "bytes32[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes32", "name": "role", "type": "bytes32"}],
        "name": "getRoleAdmin",
        "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"internalType": "address", "name": "account", "type": "address"},
        ],
        "name": "grantRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"internalType": "address", "name": "account", "type": "address"},
        ],
        "name": "hasRole",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "image",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "imageUri",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "account", "type": "address"},
            {"internalType": "address", "name": "operator", "type": "address"},
        ],
        "name": "isApprovedForAll",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "maxSupply",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "account", "type": "address"},
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "bytes", "name": "data", "type": "bytes"},
        ],
        "name": "mint",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
            {"internalType": "uint256[]", "name": "amounts", "type": "uint256[]"},
            {"internalType": "bytes", "name": "data", "type": "bytes"},
        ],
        "name": "mintBatch",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "name",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "pure",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "numberOfParts",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "partTitle",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {"inputs": [], "name": "renounceOwnership", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
    {
        "inputs": [
            {"internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"internalType": "address", "name": "account", "type": "address"},
        ],
        "name": "renounceRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "role", "type": "bytes32"},
            {"internalType": "address", "name": "account", "type": "address"},
        ],
        "name": "revokeRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "from", "type": "address"},
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
            {"internalType": "uint256[]", "name": "amounts", "type": "uint256[]"},
            {"internalType": "bytes", "name": "data", "type": "bytes"},
        ],
        "name": "safeBatchTransferFrom",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "from", "type": "address"},
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "bytes", "name": "data", "type": "bytes"},
        ],
        "name": "safeTransferFrom",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "operator", "type": "address"},
            {"internalType": "bool", "name": "approved", "type": "bool"},
        ],
        "name": "setApprovalForAll",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes4", "name": "interfaceId", "type": "bytes4"}],
        "name": "supportsInterface",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "totalSupply",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "categoryId_", "type": "bytes32"},
            {"internalType": "string", "name": "title_", "type": "string"},
            {"internalType": "string", "name": "description_", "type": "string"},
            {"internalType": "string", "name": "ipfsHash_", "type": "string"},
            {
                "components": [
                    {"internalType": "string", "name": "trait_type", "type": "string"},
                    {"internalType": "string", "name": "value", "type": "string"},
                ],
                "internalType": "struct IPartCollection.Attribute[]",
                "name": "attributes",
                "type": "tuple[]",
            },
            {"internalType": "uint256", "name": "maxSupply_", "type": "uint256"},
            {"internalType": "uint256", "name": "filledSupply_", "type": "uint256"},
        ],
        "name": "unsafeCreatePart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
            {"internalType": "uint256[]", "name": "amounts", "type": "uint256[]"},
        ],
        "name": "unsafeMintBatch",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "uri",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"}],
        "name": "zIndex",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
]

TransferSingle = "0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62"
TransferBatch = "0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb"
URI = "0x6bb7ff708619ba0610cba295a58592e0451dee2622938c8755667688daf3529b"
OrdersMatched = "0xc4109843e0b7d514e4c093114b863f8e7d8d9a458c372cd51bfe526b588006c9"

api_key = "3W817P6QNT9UIH7EFPDB5G3IEVJKZ8RKHH"

contract_addresses_punks = {
    # CryptoPunks
    "0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb": "CryptoPunks: Ͼ Token",
    "0x16f5a35647d6f03d5d3da7b35409d65ba03af3b2": "CryptoPunks: Data",
    "0xb5191de5e9ed5ce94176b7917430a8512e5ad517": "CryptoPunks: Deployer",
    "0x6ba6f2207e343923ba692e5cae646fb0f566db8d": "Cryptopunks: Old Token",
}
contract_addresses_kitties = {
    # CryptoKitties
    "0x06012c8cf97bead5deae237070f9587f8e7a266d": "CryptoKitties",
    "0xb1690c08e213a35ed9bab7b318de14420fb57d8c": "CryptoKitties",
    "0x09fe5f0236f0ea5d930197dce254d77b04128075": "CryptoKitties",
    "0xc7af99fe5513eb6710e6d5f44f9989da40f27f26": "CryptoKitties",
}

contracts_marketplace = {
    # OpenSea
    "0x939c8d89ebc11fa45e576215e2353673ad0ba18a": "OpenSea: Deployer",
    "0x9c4e9cce4780062942a7fe34fa2fa7316c872956": "OpenSea: ENS Resolver",
    "0x495f947276749ce646f68ac8c248420045cb7b5e": "OpenSea: OPENSTORE Token",
    "0x18c2e87d183c5338a9142f97db176f3832b1d6de": "OpenSea: Payments",
    "0xa5409ec958c83c3f309868babaca7c86dcb077c1": "OpenSea: Registry",
    "0x5b3256965e7c3cf26e11fcaf296dfc8807c01073": "OpenSea: Wallet",
    "0x7be8076f4ea4a4ad08075c2508e481d6c946d12b": "OpenSea: Wyvern Exchange v1",
    "0x7f268357a8c2552623316e2562d90e642bb538e5": "OpenSea: Wyvern Exchange v2",
    # Rarible
    "0xb66a603f4cfe17e3d27b87a8bfcad319856518b8": "Rarible: Asset Contract ERC1155",
    "0xf6793da657495ffeff9ee6350824910abc21356c": "Rarible: Asset Contract ERC721",
    "0x3482549fca7511267c9ef7089507c0f16ea1dcc1": "Rarible: Deployer",
    "0x81243681078bee8e251d02ee6872b1eaa6dd982a": "Rarible: ERC1155 Factory",
    "0x6d9dd3547baf4c190ab89e0103c363feaf325eca": "Rarible: ERC721 Factory",
    "0xcd4ec7b66fbc029c116ba9ffb3e59351c20b5b06": "Rarible: Exchange 1",
    "0x9757f2d2b135150bbeb65308d4a91804107cd8d6": "Rarible: Exchange Proxy",
    "0xea90cfad1b8e030b8fd3e63d22074e0aeb8e0dcd": "Rarible: External Royalties",
    "0xfca59cd816ab1ead66534d82bc21e7515ce441cf": "Rarible: RARI Token 1",
    "0x60f80121c31a0d46b5279700f9df786054aa5ee5": "Rarible: RARI Token 2",
    "0xd07dc4262bcdbf85190c01c996b4c06a461d2430": "Rarible: RARI Token 3",
    "0x1cf0df2a5a20cd61d68d4489eebbf85b8d39e18a": "Rarible: Treasury",
    "0xfdff6b56cce39482032b27140252ff4f16432785": "Rarible: Treasury 2",
    # SuperRare
    "0x8c9f364bf7a56ed058fc63ef81c6cf09c833e656": "SuperRare: Auction House",
    "0xb2d39da392f19edb27639b92adfe7edfcc96391b": "SuperRare: Deployer",
    "0x65b49f7aee40347f5a90b714be4ef086f3fe5e2c": "SuperRare: Marketplace",
    "0x5474b3abf3e58a2b32f329f3633406a0d2941e6f": "SuperRare: RARE Airdrop",
    "0xba5bde662c17e2adff1075610382b9b691296350": "SuperRare: RARE Token",
    "0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0": "SuperRare: SUPR Token",
}

all_attr = [
    {
        "Fur": {
            0: "Savannah",
            1: "Selkirk",
            2: "Chantilly",
            3: "Birman",
            4: "Koladiviya",
            5: "Bobtail",
            6: "Manul",
            7: "Pixiebob",
            8: "Siberian",
            9: "Cymric",
            10: "Chartreux",
            11: "Himalayan",
            12: "Munchkin",
            13: "Sphynx",
            14: "Ragamuffin",
            15: "Ragdoll",
            16: "Norwegianforest",
            17: "Mekong",
            18: "Highlander",
            19: "Balinese",
            20: "Lynx",
            21: "Mainecoon",
            22: "Laperm",
            23: "Persian",
            24: "Fox",
            25: "Kurilian",
            26: "Toyger",
            27: "Manx",
            28: "Lykoi",
            29: "Burmilla",
            30: "Liger",
            31: "",
        }
    },
    {
        "Patern": {
            0: "Vigilante",
            1: "Tiger",
            2: "Rascal",
            3: "Ganado",
            4: "Leopard",
            5: "Camo",
            6: "Rorschach",
            7: "Spangled",
            8: "Calicool",
            9: "Luckystripe",
            10: "Amur",
            11: "Jaguar",
            12: "Spock",
            13: "Mittens",
            14: "Totes_14",
            15: "Totesbasic",
            16: "Splat",
            17: "Thunderstruck",
            18: "Dippedcone",
            19: "Highsociety",
            20: "Tigerpunk",
            21: "Henna",
            22: "Arcreactor",
            23: "Totes_23",
            24: "Scorpius",
            25: "Razzledazzle",
            26: "Hotrod",
            27: "Allyouneed",
            28: "Avatar",
            29: "Gyre",
            30: "Moonrise",
            31: "Totes_31",
        }
    },
    {
        "Eye colour": {
            0: "Thundergrey",
            1: "Gold",
            2: "Topaz",
            3: "Mintgreen",
            4: "Isotope",
            5: "Sizzurp",
            6: "Chestnut",
            7: "Strawberry",
            8: "Sapphire",
            9: "Forgetmenot",
            10: "Dahlia",
            11: "Coralsunrise",
            12: "Olive",
            13: "Doridnudibranch",
            14: "Parakeet",
            15: "Cyan",
            16: "Pumpkin",
            17: "Limegreen",
            18: "Bridesmaid",
            19: "Bubblegum",
            20: "Twilightsparkle",
            21: "Palejade",
            22: "Pinefresh",
            23: "Eclipse",
            24: "Babypuke",
            25: "Downbythebay",
            26: "Autumnmoon",
            27: "Oasis",
            28: "Gemini",
            29: "Dioscuri",
            30: "Kaleidoscope",
            31: "",
        }
    },
    {
        "Eye Shape": {
            0: "Swarley",
            1: "Wonky",
            2: "Serpent",
            3: "Googly",
            4: "Otaku",
            5: "Simple",
            6: "Crazy",
            7: "Thicccbrowz",
            8: "Caffeine",
            9: "Wowza",
            10: "Baddate",
            11: "Asif",
            12: "Chronic",
            13: "Slyboots",
            14: "Wiley",
            15: "Stunned",
            16: "Chameleon",
            17: "Alien",
            18: "Fabulous",
            19: "Raisedbrow",
            20: "Tendertears",
            21: "Hacker",
            22: "Sass",
            23: "Sweetmeloncakes",
            24: "Oceanid",
            25: "Wingtips",
            26: "Firedup",
            27: "Buzzed",
            28: "Bornwithit",
            29: "Candyshoppe",
            30: "Drama",
            31: "",
        }
    },
    {
        "Base colour": {
            0: "Shadowgrey",
            1: "Salmon",
            2: "Meowgarine",
            3: "Orangesoda",
            4: "Cottoncandy",
            5: "Mauveover",
            6: "Aquamarine",
            7: "Nachocheez",
            8: "Harbourfog",
            9: "Cinderella",
            10: "Greymatter",
            11: "Tundra",
            12: "Brownies",
            13: "Dragonfruit",
            14: "Hintomint",
            15: "Bananacream",
            16: "Cloudwhite",
            17: "Cornflower",
            18: "Oldlace",
            19: "Koala",
            20: "Lavender",
            21: "Glacier",
            22: "Redvelvet",
            23: "Verdigris",
            24: "Icicle",
            25: "Onyx",
            26: "Hyacinth",
            27: "Martian",
            28: "Hotcocoa",
            29: "Shamrock",
            30: "Firstblush",
            31: "",
        }
    },
    {
        "Highlight Colour": {
            0: "Shadowgrey",
            1: "Salmon",
            2: "Meowgarine",
            3: "Orangesoda",
            4: "Cottoncandy",
            5: "Mauveover",
            6: "Aquamarine",
            7: "Nachocheez",
            8: "Harbourfog",
            9: "Cinderella",
            10: "Greymatter",
            11: "Tundra",
            12: "Brownies",
            13: "Dragonfruit",
            14: "Hintomint",
            15: "Bananacream",
            16: "Cloudwhite",
            17: "Cornflower",
            18: "Oldlace",
            19: "Koala",
            20: "Lavender",
            21: "Glacier",
            22: "Redvelvet",
            23: "Verdigris",
            24: "Icicle",
            25: "Onyx",
            26: "Hyacinth",
            27: "Martian",
            28: "Hotcocoa",
            29: "Shamrock",
            30: "Firstblush",
            31: "",
        }
    },
    {
        "Accent colour": {
            0: "Belleblue",
            1: "Sandalwood",
            2: "Peach",
            3: "Icy",
            4: "Granitegrey",
            5: "Cashewmilk",
            6: "Kittencream",
            7: "Emeraldgreen",
            8: "Kalahari",
            9: "Shale",
            10: "Purplehaze",
            11: "Hanauma",
            12: "Azaleablush",
            13: "Missmuffett",
            14: "Morningglory",
            15: "Frosting",
            16: "Daffodil",
            17: "Flamingo",
            18: "Buttercup",
            19: "Bloodred",
            20: "Atlantis",
            21: "Summerbonnet",
            22: "Periwinkle",
            23: "Patrickstarfish",
            24: "Seafoam",
            25: "Cobalt",
            26: "Mallowflower",
            27: "Mintmacaron",
            28: "Sully",
            29: "Fallspice",
            30: "Dreamboat",
            31: "",
        }
    },
    {
        "Wild": {
            0: "WE00",
            1: "WE01",
            2: "WE02",
            3: "WE03",
            4: "WE04",
            5: "WE05",
            6: "WE06",
            7: "WE07",
            8: "WE08",
            9: "WE09",
            10: "WE10",
            11: "WE11",
            12: "WE12",
            13: "WE13",
            14: "WE14",
            15: "WE15",
            16: "Littlefoot",
            17: "Elk",
            18: "Ducky",
            19: "Trioculus",
            20: "Daemonwings",
            21: "Featherbrain",
            22: "Flapflap",
            23: "Daemonhorns",
            24: "Dragontail",
            25: "Aflutter",
            26: "Foghornpawhorn",
            27: "Unicorn",
            28: "Dragonwings",
            29: "Alicorn",
            30: "Wyrm",
            31: "WE31",
        }
    },
    {
        "Mouth": {
            0: "Whixtensions",
            1: "Wasntme",
            2: "Wuvme",
            3: "Gerbil",
            4: "Confuzzled",
            5: "Impish",
            6: "Belch",
            7: "Rollercoaster",
            8: "Beard",
            9: "Pouty",
            10: "Saycheese",
            11: "Grim",
            12: "Fangtastic",
            13: "Moue",
            14: "Happygokitty",
            15: "Soserious",
            16: "Cheeky",
            17: "Starstruck",
            18: "Samwise",
            19: "Ruhroh",
            20: "Dali",
            21: "Grimace",
            22: "Majestic",
            23: "Tongue",
            24: "Yokel",
            25: "Topoftheworld",
            26: "Neckbeard",
            27: "Satiated",
            28: "Walrus",
            29: "Struck",
            30: "Delite",
            31: "",
        }
    },
    {
        "Environment": {
            0: "EN00",
            1: "EN01",
            2: "EN02",
            3: "EN03",
            4: "EN04",
            5: "EN05",
            6: "EN06",
            7: "EN07",
            8: "EN08",
            9: "EN09",
            10: "EN10",
            11: "EN11",
            12: "EN12",
            13: "EN13",
            14: "EN14",
            15: "EN15",
            16: "Salty",
            17: "Dune",
            18: "Juju",
            19: "Tinybox",
            20: "Myparade",
            21: "Finalfrontier",
            22: "Metime",
            23: "Drift",
            24: "Secretgarden",
            25: "Frozen",
            26: "Roadtogold",
            27: "Jacked",
            28: "Floorislava",
            29: "Prism",
            30: "Junglebook",
            31: "EN31",
        }
    },
    {
        "Secret": {
            0: "SE00",
            1: "SE01",
            2: "SE02",
            3: "SE03",
            4: "SE04",
            5: "SE05",
            6: "SE06",
            7: "SE07",
            8: "SE08",
            9: "SE09",
            10: "SE10",
            11: "SE11",
            12: "SE12",
            13: "SE13",
            14: "SE14",
            15: "SE15",
            16: "SE16",
            17: "SE17",
            18: "SE18",
            19: "SE19",
            20: "SE20",
            21: "SE21",
            22: "SE22",
            23: "SE23",
            24: "SE24",
            25: "SE25",
            26: "SE26",
            27: "SE27",
            28: "SE28",
            29: "SE29",
            30: "SE30",
            31: "SE31",
        }
    },
    {
        "PU": {
            0: "PU00",
            1: "PU01",
            2: "PU02",
            3: "PU03",
            4: "PU04",
            5: "PU05",
            6: "PU06",
            7: "PU07",
            8: "PU08",
            9: "PU09",
            10: "PU10",
            11: "PU11",
            12: "PU12",
            13: "PU13",
            14: "PU14",
            15: "PU15",
            16: "PU16",
            17: "PU17",
            18: "PU18",
            19: "PU19",
            20: "PU20",
            21: "PU21",
            22: "PU22",
            23: "PU23",
            24: "PU24",
            25: "PU25",
            26: "PU26",
            27: "PU27",
            28: "PU28",
            29: "PU29",
            30: "PU30",
            31: "PU31",
        }
    },
]


events_punk = {
    "0x05af636b70da6819000c49f85b21fa82081c632069bb626f30932034099107d8": "PunkTransfer",
    "0x6f30e1ee4d81dcc7a8a478577f65d2ed2edb120565960ac45fe7c50551c87932": "PunkBidWithdrawn",
    "0x3c7b682d5da98001a9b8cbda6c647d2c63d698a4184fd1d55e2ce7b66f5d21eb": "PunkOffered",
    "0xb0e0a660b4e50f26f0b7ce75c24655fc76cc66e3334a54ff410277229fa10bd4": "PunkNoLongerForSale",
    "0x58e5d5a525e3b40bc15abaa38b5882678db1ee68befd2f60bafe3a7fd06db9e3": "PunkBought",
    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef": "Transfer",
    "0x5b859394fabae0c1ba88baffe67e751ab5248d2e879028b8c8d6897b0519f56a": "PunkBidEntered",
}

events_kitties = {
    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef": "Transfer",
    "0xa9c8dfcda5664a5a124c713e386da27de87432d5b668e79458501eb296389ba7": "AuctionCreated",
    "0x2809c7e17bf978fbc7194c0a694b638c4215e9140cacc6c38ca36010b45697df": "AuctionCancelled",
    "0x0a5311bd2a6608f08a180df2ee7c5946819a649b204b554bb8e39825b2c50ad5": "Birth",
    "0x4fcc30d90a842164dd58501ab874a101a3749c3d4747139cefe7c876f4ccebd2": "AuctionSuccessful",
    "0x999fa95b06ad12b3436bab902713e383705707923f9d7c75f5432b28a6487010": "DepositKittyAndMintToken",
    "0x2f467b677a4a63395bce26e8731fa49a02cd892ddeaf266650b403f140ba4590": "BurnTokenAndWithdrawKitty",
}
